In [1]:
#class project 1
#import pandas
import pandas as cp

#reading the file1
data = cp.read_csv("Top-Apps-in-Google-Play.csv")

#displaying the first 7 rows file1
dg = data.head(7)

dg

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False
1,2,YouTube,com.google.android.youtube,Video Players & Editors,Google LLC,https://support.google.com/youtube/topic/24225...,ytandroid-support@google.com,Teen,True,False
2,3,Google,com.google.android.googlequicksearchbox,Tools,Google LLC,https://www.google.com/search/about/,apps-help@google.com,Everyone,True,False
3,4,Google Maps - Navigate & Explore,com.google.android.apps.maps,Travel & Local,Google LLC,http://maps.google.com/about/,apps-help@google.com,Everyone,True,False
4,5,Google Text-to-Speech,com.google.android.tts,Tools,Google LLC,http://www.google.com/,tts-feedback@google.com,Everyone,False,False
5,6,Google Chrome: Fast & Secure,com.android.chrome,Communication,Google LLC,http://www.google.com/chrome/android,apps-help@google.com,Everyone,False,False
6,7,Gmail,com.google.android.gm,Communication,Google LLC,http://support.google.com/mail/bin/topic.py?hl...,apps-help@google.com,Everyone,True,False

In [2]:
#class project 1
#import pandas
import pandas as cp

#reading the file2
data2 = cp.read_csv("BTC_DATA_V3.0.csv")

#displaying the first 7 rows file2
df = data2.head(7)

df

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%
1  24-Mar-22  44013.0  42911.0  44251.0  42658.0  491.66M    2.57%
2  23-Mar-22  42912.0  42373.0  43027.0  41795.0  433.96M    1.27%
3  22-Mar-22  42373.0  41022.0  43327.9  40893.0  537.06M    3.29%
4  21-Mar-22  41022.0  41282.0  41532.0  40530.0  406.62M   -0.62%
5  20-Mar-22  41276.0  42241.0  42301.0  40922.0  308.45M   -2.27%
6  19-Mar-22  42233.0  41768.0  42386.0  41529.6  224.59M    1.11%

In [3]:
#class project 1
#import pandas
import pandas as cp

#reading the file1
data = cp.read_csv("Top-Apps-in-Google-Play.csv")

#selecting the first 3 columns file1
dg = cp.DataFrame(data)

dg[['App Name', 'App Id', 'Category']]

,App Name,App Id,Category
0,Google Play services,com.google.android.gms,Tools
1,YouTube,com.google.android.youtube,Video Players & Editors
2,Google,com.google.android.googlequicksearchbox,Tools
3,Google Maps - Navigate & Explore,com.google.android.apps.maps,Travel & Local
4,Google Text-to-Speech,com.google.android.tts,Tools
...,...,...,...
65,Clock,com.google.android.deskclock,Tools
66,Spotify: Listen to podcasts & find music you love,com.spotify.music,Music & Audio
67,Google Translate,com.google.android.apps.translate,Tools
68,Samsung Notes,com.samsung.android.app.notes,Productivity
69,Calculator,com.google.android.calculator,Tools

In [4]:
#class project 1
#import pandas
import pandas as cp

#reading the file2
data2 = cp.read_csv("BTC_DATA_V3.0.csv")

#selecting the first 3 columns file2
df = cp.DataFrame(data2)

df[['Date', 'Price', 'Open']]

           Date    Price     Open
0     25-Mar-22  44331.0  44013.0
1     24-Mar-22  44013.0  42911.0
2     23-Mar-22  42912.0  42373.0
3     22-Mar-22  42373.0  41022.0
4     21-Mar-22  41022.0  41282.0
...         ...      ...      ...
1484   2-Mar-18  10827.7  10904.5
1485   1-Mar-18  10904.5  10335.1
1486  28-Feb-18  10333.9  10584.4
1487  27-Feb-18  10594.4  10287.8
1488  26-Feb-18  10285.1   9590.9

[1489 rows x 3 columns]

In [5]:
#class project 1
#import pandas
import pandas as cp

#reading the file1
data = cp.read_csv("Top-Apps-in-Google-Play.csv")

#displaying a row and the header file 1
dg = data.head(1)

dg

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False

In [6]:
#class project 1
#import pandas
import pandas as cp

#reading the file2
data2 = cp.read_csv("BTC_DATA_V3.0.csv")

#displaying a row and the header file 2
df = data2.head(1)

df

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%

In [1]:
#project2

#import pandas
import pandas as ac

#creating the dictionary
products = {'Export': ["Cocoa Butter", "Cake", "Liquor", "Cocoa Powder"],
            'Segments': ["Refreshment Beverages", "Confectionery", "Intermediate Cocoa Products", ""],
            'Brands': ["Refreshment Beverages", "Confectionery", "Intermediate Cocoa Products", ""]}

# creating a dataframe from a dictionary 
cf = ac.DataFrame(products)

# saving the dataframe and creating the file
cf.to_csv('cadbury_market.csv')

print('File has been created')

File has been created